#!/bin/zsh

normal=`tput sgr0`
bold=`tput bold`
orange=`tput setaf 208`
green=`tput setaf 46`
magenta=`tput setaf 9`
red=`tput setaf 196`
WARN="${bold}[${orange}WARNING${normal}${bold}] "
HINT="${bold}[${magenta}HINT${normal}${bold}] "
COMPLETE="${bold}[${green}COMPLETE${normal}${bold}] "
ERROR="${bold}[${red}ERROR${normal}${bold}] "

installCustomCommands() {
     if [ ! -d $HOME/.42Commands ]; then
        mkdir $HOME/.42Commands
        cp $HOME/.42utils/utilsV1/42Commands/* $HOME/.42Commands/
        echo "${COMPLETE}Correct 42Commands is installed, reload the terminal to complete.\n"
    else
        echo "${WARN}Correct 42Commands is installed, reload the terminal to complete.\n"
    fi
}

customConfigP10k() {
    if [ ! -f $HOME/.p10k.zsh ]; then
        cp $HOME/.42utils/exec/main/.p10k.zsh $HOME/
        echo "${COMPLETE}Correct p10k theme is installed, reload the terminal to complete.\n"
    else
        echo "${WARN}Correct p10k theme is installed, reload the terminal to complete."
    fi
}

installFonts() {
    if [ ! -f  $HOME/Library/Fonts/MesloLGS\ NF\ Regular.ttf ]; then
        cp $HOME/.42utils/exec/main/Fonts/* $HOME/Library/Fonts/
        echo "${COMPLETE}Correct Font is installed, reload the system if you don't see.\n"
    else
        echo "${WARN}Correct Font is installed, reload the system if you don't see."
    fi
}

installPower10kBasic() {
    if [ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ]; then
        result_power_10k_install=$(git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k)
        echo "\n${COMPLETE}powerlevel10k is installed\n"
    else
        echo "\n${WARN}powerlevel10k is installed"
    fi
    if [ -d $HOME/.zshrc ]; then
        echo "${WARN}deleted original zshrc"
        rm $HOME/.zshrc
    fi
    
    cp $HOME/.42utils/exec/main/zsh_config $HOME/.zshrc

    if [ -f $HOME/.zshrc ]; then
        echo "${WARN}Correct zshrc file is installed"
    else
        echo "${ERROR}Error with zshrc install"
    fi
}

installPowerAutoSuggestions() {
    if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
        result_auto_suggestions=$(git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions)
        echo "\n${COMPLETE}zsh-autosuggestions is installed\n"
    else
        echo "${WARN}zsh-autosuggestions is installed"
    fi
}

#Install Methods

installTerminalCustom() {
    installPower10kBasic
    installPowerAutoSuggestions
    installFonts
    customConfigP10k
    installCustomCommands
}

checkInstallation() {
    #Check Suggestions
    if [ ! -d ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions ]; then
        echo "\n${ERROR}zsh-autosuggestions is not installed"
    else
        echo "\n${COMPLETE}zsh-autosuggestions is installed"
    fi

    #Check Power10k
    if [ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ]; then
        echo "${ERROR}powerlevel10k is not installed"
    else
        echo "${COMPLETE}powerlevel10k is installed"
    fi

    #Check Fonts
    if [ ! -f  $HOME/Library/Fonts/MesloLGS\ NF\ Regular.ttf ]; then
         echo "${ERROR}Correct Font is not installed"
    else
        echo "${COMPLETE}Correct Font is installed"
    fi

    #Check p10k-custom
    if [ ! -f $HOME/.p10k.zsh ]; then
        echo "${ERROR}Correct p10k theme is not installed"
    else
        echo "${COMPLETE}Correct p10k theme is installed"
    fi

    #Check 42Commands
    if [ ! -d $HOME/.42Commands ]; then
        echo "${ERROR}Correct 42Commands is not installed"
    else
        echo "${COMPLETE}Correct 42Commands is installed"
    fi
}

normalUpdate() {
    cd $HOME/.42utils
    message=$(git pull)
    if [[ "$message" == "Already up to date." ]]; then
        echo "\n${WARN}$message"
    else
        echo "\n${COMPLETE}Updated all."
    fi
}

demoProgramUpdate() {
    cd $HOME/.42utils
    demo=$(git checkout develop)
    message=$(git pull)
    if [[ "$message" == "Already up to date." ]]; then
        echo "\n${WARN}$message"
    else
        echo "\n${COMPLETE}Updated all."
    fi
}

Help()
{
   echo ""
   echo "${bold}42Hub installPackage ${red}beta${normal}${bold} 0.1 by zxcvbinz${normal}"
   echo
   echo "${HINT}Syntax: 42Hub ${red}[${normal}${bold}install | check | update${red}]${normal}${bold}"
   echo
}

if [[ "$1" == "" ]]; then
    Help
elif [[ "$1" == "check" ]]; then
    checkInstallation
elif [[ "$1" == "update" ]]; then
    if [[ "$2" == "" ]]; then
        normalUpdate
    elif [[ "$2" == "demo" ]]; then
        demoProgramUpdate
    fi
elif [[ "$1" == "install" ]]; then
    installTerminalCustom
fi